spring.application.name=runner-circle-api

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health

runnercircle.upload.dir=uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

runnercircle.jwt.secret=${JWT_SECRET}
runnercircle.jwt.expiracao-padrao=${JWT_EXPIRATION:3600000}
runnercircle.jwt.expiracao-lembrar-me=${JWT_EXPIRATION_REMEMBER_ME:2592000000}
